<?
/**
 * Author Template View
 *
 * @package    Molajo
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2014-2015 Amy Stephen. All rights reserved.
 */
?>

<div class="row">
    <div class="large-12 columns">
        <div class="panel">
            <h5><?= $this->row->author_full_name; ?></h5>
            <? if ($this->row->author_parameters->display_gravatar == 1) : ?>
                <p>
                    <img class="gravatar float_left" src="<?= $this->row->author_email; ?>"
                         alt="[<?= $this->row->author_full_name; ?>]">
                </p>
            <? endif; ?>
            <p>
                <a href="" title="<?= $this->row->author_full_name; ?>">
                    <?= $this->row->author_full_name; ?>
                </a>
            </p>
            <? if ($this->row->author_parameters->display_phone == 1) : ?>
                <p itemprop="tel">
                    Custom field phone
                </p>
            <? endif; ?>
            <? if ($this->row->author_parameters->display_email == 1) : ?>
                <h5>
                    <?= $this->row->author_email; ?>
                </h5>
            <? endif; ?>
            <p>
                About me
            </p>
        </div>
    </div>
</div>
