<?
/**
 * Foundation Theme
 *
 * @package    Molajo
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2014-2015 Amy Stephen. All rights reserved.
 */
?>
<!DOCTYPE html>
<!--[if IE 8]>
<html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <title>Molajo</title>
    <link rel="stylesheet" href="/Css/normalize.css">
    <link rel="stylesheet" href="/Css/webicons.css">
    <link rel="stylesheet" href="/Css/foundation-icons.css"/>
    <link rel="stylesheet" href="/Css/foundation.css">
    <link rel="stylesheet" href="/Css/customize.css">
    <link rel="stylesheet" href="/Css/responsive-tables.css"/>
    <link rel="stylesheet" href="/Css/foundation-datepicker.css">
    <script src="/Js/vendor/custom.modernizr.js"></script>
    <script src="/Ckeditor/ckeditor.js"></script>
    <script>
        CKEDITOR.replace('editor1');
    </script>
    <script>
        window.onload = function () {
            CKEDITOR.replace('editor1');
        };
    </script>
</head>
<body>
<a id="top"></a>

<div class="page-wrap">
    {I Navbar I}
    <div id="wrapper" class="row">
        <div class="large-12 columns">
            {I Breadcrumbs I}
            {I Messages I}
            {I Header I}
            {I Page I}
        </div>
    </div>
    <footer class="site-footer">
        {I Footer I}
    </footer>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
<script src="/Js/foundation/foundation.js"></script>
<script src="/Js/foundation/foundation.topbar.js"></script>
<script src="/Js/foundation/foundation.tooltip.js"></script>
<script src="/Js/foundation/foundation.accordion.js"></script>
<script src="/Js/foundation/foundation.alert.js"></script>
<script src="/Js/foundation/foundation.abide.js"></script>
<script src="/Js/foundation/foundation.form.js"></script>
<script src="/Js/responsive-tables.js"></script>
<script src="/Js/Defer/document.js"></script>
<script src="/Js/Defer/checkall.js"></script>
<script src="/Js/Defer/hideshow.js"></script>
</body>
</html>
