<?
/**
 * @package    Molajo
 * @copyright  2014-2015 Amy Stephen. All rights reserved.
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 */
$base_url = $this->plugin_data->page->urls['base'];
$page_url = $this->plugin_data->page->urls['page'];
$home_url = $this->plugin_data->page->urls['home'];

$thru_now = '';

$copyright_statement = '© 2014-2015 Molajo';
?>
<div class="row">
    <div class="small-12 medium-12 large-12 columns">
        <ul class="footer-links">
            <li><a href="<?= $page_url; ?>#top">&uarr;
                    {T Back to Top T}
                </a>
            </li>
            <li><a href="<?= $base_url; ?>pages/about-us">
                    {T About Us T}
                </a>
            </li>
            <li><a href="<?= $base_url; ?>pages/contact-us">
                    {T Contact Us T}
                </a>
            </li>
            <li><a href="<?= $base_url; ?>pages/privacy-policy">
                    {T Privacy Policy T}
                </a>
            </li>
            <li><a href="<?= $base_url; ?>pages/site-map">
                    {T Site Map T}
                </a>
            </li>
        </ul>
        <p class="copyright">
            <?= $copyright_statement; ?>
        </p>
    </div>
</div>
