<?
/**
 * Blog Template View
 *
 * @package    Molajo
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2014-2015 Amy Stephen. All rights reserved.
 */
?>
<article class="blog">
    <h3>
        <a href="<?= $this->row->catalog_sef_request; ?>">
            <?= $this->row->title; ?>
        </a>
    </h3>
    <h6>{T Written by T}
        <a href="#">
            <? echo $this->row->author_full_name; ?>
        </a>
        {T on T}
        <?=
        $this->row->start_publishing_datetime_day_name
        . ', ' . $this->row->start_publishing_datetime_month_name
        . ' ' . $this->row->start_publishing_datetime_dd
        . ', ' . $this->row->start_publishing_datetime_ccyy; ?>.
    </h6>
    <? if ($this->row->customfields->image1 == '') :
    else : ?>
        <figure class="float_left image1">
            <img src="<?= $this->row->customfields->image1; ?>" alt="<?= $this->row->customfields->image_caption1; ?>">
            <? if ($this->row->customfields->image_caption1 == '') :
            else : ?>
                <figcaption><?= $this->row->customfields->image_caption1; ?></figcaption>
            <?  endif; ?>
        </figure>
    <? endif;
    if ($this->row->content_text_introductory == '') :
    else : ?>
        <div class="introductory"><?= $this->row->content_text_introductory; ?></div>
    <? endif; ?>
    <p class="readmore">
        <a href="<?= $this->row->catalog_sef_request; ?>">
            {T Read more T}&rarr;
        </a>
    </p>
</article>
