<?
/**
 * Article Template View
 *
 * @package    Molajo
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2014-2015 Amy Stephen. All rights reserved.
 */
if ((int)$this->parameters->enable_response_comments === 1 && (int)$this->parameters->enable_response_comments == 1) {
    $do_comments = true;
} else {
    $do_comments = false;
}
$id    = 71;
$start = substr($this->row->start_publishing_datetime, 0, 10);
$open  = $this->parameters->enable_response_comment_form_open_days;
?>
<h3>
    <?= $this->row->title; ?>
    <small>{T Written by T}
        <a href="#">
            <?= $this->row->created_by_full_name; ?>
        </a>
        {T on T}
        <?=
        $this->row->start_publishing_datetime_day_name
        . ', ' . $this->row->start_publishing_datetime_month_name
        . ' ' . $this->row->start_publishing_datetime_dd
        . ', ' . $this->row->start_publishing_datetime_ccyy;
        ?>.
    </small>
</h3>

<? if (isset($this->row->customfields->image2) && $this->row->customfields->image2 !== '') : ?>
    <figure class="right panel">
        <img src="<?= $this->row->customfields->image2; ?>" alt="">
        <? if ($this->row->customfields->image_caption2 == '') :
        else : ?>
            <figcaption><?= $this->row->customfields->image_caption2; ?></figcaption>
        <? endif; ?>
    </figure>
<? endif; ?>

<?= $this->row->content_text_fulltext; ?>

<? if (isset($this->row->customfields->image3) && $this->row->customfields->image3 !== '') : ?>
    <figure class="left panel">
        <img src="<?= $this->row->customfields->image3; ?>" alt="<?= $this->row->customfields->image_caption3; ?>"
             class="img">
        <? if ($this->row->customfields->image_caption3 == '') :
        else : ?>
            <figcaption><?= $this->row->customfields->image_caption3; ?></figcaption>
        <? endif; ?>
    </figure>
<? endif; ?>

    {I template=Author wrap_class=author-profile author=<?= $this->row->created_by; ?> I}

<? if ($do_comments === true) : ?>
    <section>
        {I template=Comments source_id=<?= $id; ?> start_publish=<?= $start; ?> open_days=<?= $open; ?> I}
    </section>
<? endif;
