<?
/**
 * @package    Molajo
 * @copyright  2014-2015 Amy Stephen. All rights reserved.
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 */
$parameters = $this->runtime_data->resource->parameters;
$page_url   = $this->runtime_data->request->data->url;
?>
<nav class="row">
    <div class="large-5 columns">
        <? if (count($this->plugin_data->grid_actions) > 0) : ?>
            <form method="post" action="" enctype="multipart/form-data">
                <ul class="button-group">
                    <li>
                        <select>
                            <option value="">{T Actions T}</option>
                            <? foreach ($this->plugin_data->datalist_actions as $item) { ?>
                                <option value="<?= $item->action; ?>">
                                    {T <?= $item->name; ?> T}
                                </option>
                            <? } ?>
                        </select>
                    </li>
                    <li>
                    <span data-tooltip class="has-tip" title="{T Apply action to selected items in grid. T}">
                        <a href="#" class="radius tiny button">
                            {T Apply T}
                        </a>
                    </span>
                    </li>
                </ul>
            </form>
        <? endif; ?>
    </div>
    <div class="large-7 columns">
        <ul class="button-group">
            <? //if ((int)$parameters->grid_toolbar_button_new === 1) : ?>
            <li>
                <span data-tooltip class="has-tip" title="{T New T}">
                    <a id="toolbar-new-button" href="#" class="radius tiny button">
                        <i class="fi-page-add" alt="{T New T}"></i>
                    </a>
                </span>
            </li>
            <? //endif; ?>
            <? //if ((int)$parameters->grid_toolbar_button_copy == 1) : ?>
            <li>
                <span data-tooltip class="has-tip" title="{T Copy T}">
                    <a id="toolbar-copy-button" href="#" class="radius tiny button">
                        <i class="fi-page-copy" alt="{T Copy T}"></i>
                    </a>
                </span>
            </li>
            <? //endif; ?>
            <? //if ((int)$parameters->grid_toolbar_button_filter == 1) : ?>
            <li>
                <span data-tooltip class="has-tip" title="{T Filters T}">
                    <a id="toolbar-filters-button" href="#" class="radius tiny button">
                        <i class="fi-filter" alt="{T Filter T}"></i>
                    </a>
                </span>
            </li>
            <? //endif; ?>
            <? //if ((int)$parameters->grid_toolbar_button_categories == 1) : ?>
            <li>
                <span data-tooltip class="has-tip"
                      title="{T Categories T}">
                    <a id="toolbar-categories-button" href="#" class="radius tiny button">
                        <i class="fi-map" alt="{T Categorize T}"></i>
                    </a>
                </span>
            </li>
            <? //endif; ?>
            <? //if ((int)$parameters->grid_toolbar_button_tags == 1) : ?>
            <li>
                <span data-tooltip class="has-tip" title="{T Tags T}">
                    <a id="toolbar-tags-button" href="#" class="radius tiny button">
                        <i class="fi-price-tag" alt="{T Tag T}"></i>
                    </a>
                </span>
            </li>
            <? //endif; ?>
            <? //if ((int)$parameters->grid_toolbar_button_permissions == 1) : ?>
            <li>
                <span data-tooltip class="has-tip"
                      title="{T Permissions T}">
                    <a id="toolbar-permissions-button" href="#" class="radius tiny button">
                        <i class="fi-torsos-all" alt="{T Permission T}"></i>
                    </a>
                </span>
            </li>
            <? //endif; ?>
        </ul>
    </div>
</nav>
